from utils.colors import BLACK

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 400
SCREEN_DIVIDER = 400
SCREEN_COLOR = BLACK
SCREEN_TITLE = 'visualize MNIST'


class NN_SIZE:
    NUMBER_OF_LAYER = 3

    INPUT = (28, 28)
    LAYER1 = (16, 16)
    LAYER2 = (4, 4)
    LAYER3 = (10, 1)
    